// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// blendPT3d_cpp
DataFrame blendPT3d_cpp(const DataFrame nearestPt, const DataFrame firstNode, const DataFrame lastNode, IntegerVector segID);
RcppExport SEXP _GISnetwork3D_blendPT3d_cpp(SEXP nearestPtSEXP, SEXP firstNodeSEXP, SEXP lastNodeSEXP, SEXP segIDSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame >::type nearestPt(nearestPtSEXP);
    Rcpp::traits::input_parameter< const DataFrame >::type firstNode(firstNodeSEXP);
    Rcpp::traits::input_parameter< const DataFrame >::type lastNode(lastNodeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type segID(segIDSEXP);
    rcpp_result_gen = Rcpp::wrap(blendPT3d_cpp(nearestPt, firstNode, lastNode, segID));
    return rcpp_result_gen;
END_RCPP
}
// calCost_net3d_THF_cpp
DataFrame calCost_net3d_THF_cpp(const DataFrame lines_df, const IntegerVector uniqueL1, double pSlope);
RcppExport SEXP _GISnetwork3D_calCost_net3d_THF_cpp(SEXP lines_dfSEXP, SEXP uniqueL1SEXP, SEXP pSlopeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame >::type lines_df(lines_dfSEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type uniqueL1(uniqueL1SEXP);
    Rcpp::traits::input_parameter< double >::type pSlope(pSlopeSEXP);
    rcpp_result_gen = Rcpp::wrap(calCost_net3d_THF_cpp(lines_df, uniqueL1, pSlope));
    return rcpp_result_gen;
END_RCPP
}
// calCost_net3d_CHF_cpp
DataFrame calCost_net3d_CHF_cpp(const DataFrame lines_df, const IntegerVector uniqueL1, double pSlope, double a, double b, double c, double d, double e);
RcppExport SEXP _GISnetwork3D_calCost_net3d_CHF_cpp(SEXP lines_dfSEXP, SEXP uniqueL1SEXP, SEXP pSlopeSEXP, SEXP aSEXP, SEXP bSEXP, SEXP cSEXP, SEXP dSEXP, SEXP eSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame >::type lines_df(lines_dfSEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type uniqueL1(uniqueL1SEXP);
    Rcpp::traits::input_parameter< double >::type pSlope(pSlopeSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type e(eSEXP);
    rcpp_result_gen = Rcpp::wrap(calCost_net3d_CHF_cpp(lines_df, uniqueL1, pSlope, a, b, c, d, e));
    return rcpp_result_gen;
END_RCPP
}
// calSlope_net3d_cpp
NumericVector calSlope_net3d_cpp(const DataFrame fromNode_df, const DataFrame toNode_df, const IntegerVector uniqueL1, const std::string& unit);
RcppExport SEXP _GISnetwork3D_calSlope_net3d_cpp(SEXP fromNode_dfSEXP, SEXP toNode_dfSEXP, SEXP uniqueL1SEXP, SEXP unitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame >::type fromNode_df(fromNode_dfSEXP);
    Rcpp::traits::input_parameter< const DataFrame >::type toNode_df(toNode_dfSEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type uniqueL1(uniqueL1SEXP);
    Rcpp::traits::input_parameter< const std::string& >::type unit(unitSEXP);
    rcpp_result_gen = Rcpp::wrap(calSlope_net3d_cpp(fromNode_df, toNode_df, uniqueL1, unit));
    return rcpp_result_gen;
END_RCPP
}
// closestPT3d_cpp
DataFrame closestPT3d_cpp(DataFrame point_df, DataFrame lines_df);
RcppExport SEXP _GISnetwork3D_closestPT3d_cpp(SEXP point_dfSEXP, SEXP lines_dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type point_df(point_dfSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type lines_df(lines_dfSEXP);
    rcpp_result_gen = Rcpp::wrap(closestPT3d_cpp(point_df, lines_df));
    return rcpp_result_gen;
END_RCPP
}
// connect3d_pair_cpp
DataFrame connect3d_pair_cpp(const DataFrame pt1, const DataFrame pt2);
RcppExport SEXP _GISnetwork3D_connect3d_pair_cpp(SEXP pt1SEXP, SEXP pt2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame >::type pt1(pt1SEXP);
    Rcpp::traits::input_parameter< const DataFrame >::type pt2(pt2SEXP);
    rcpp_result_gen = Rcpp::wrap(connect3d_pair_cpp(pt1, pt2));
    return rcpp_result_gen;
END_RCPP
}
// connect3d_ManyToMany_cpp
DataFrame connect3d_ManyToMany_cpp(const DataFrame pt1, const DataFrame pt2);
RcppExport SEXP _GISnetwork3D_connect3d_ManyToMany_cpp(SEXP pt1SEXP, SEXP pt2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame >::type pt1(pt1SEXP);
    Rcpp::traits::input_parameter< const DataFrame >::type pt2(pt2SEXP);
    rcpp_result_gen = Rcpp::wrap(connect3d_ManyToMany_cpp(pt1, pt2));
    return rcpp_result_gen;
END_RCPP
}
// dist3d_pt2pt_cpp
NumericMatrix dist3d_pt2pt_cpp(NumericMatrix points1, NumericMatrix points2);
RcppExport SEXP _GISnetwork3D_dist3d_pt2pt_cpp(SEXP points1SEXP, SEXP points2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type points1(points1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type points2(points2SEXP);
    rcpp_result_gen = Rcpp::wrap(dist3d_pt2pt_cpp(points1, points2));
    return rcpp_result_gen;
END_RCPP
}
// dist3d_pt2line_cpp
NumericMatrix dist3d_pt2line_cpp(NumericMatrix points, DataFrame lines_df);
RcppExport SEXP _GISnetwork3D_dist3d_pt2line_cpp(SEXP pointsSEXP, SEXP lines_dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type lines_df(lines_dfSEXP);
    rcpp_result_gen = Rcpp::wrap(dist3d_pt2line_cpp(points, lines_df));
    return rcpp_result_gen;
END_RCPP
}
// dist3d_pt2pt_pair_cpp
NumericVector dist3d_pt2pt_pair_cpp(NumericMatrix points1, NumericMatrix points2);
RcppExport SEXP _GISnetwork3D_dist3d_pt2pt_pair_cpp(SEXP points1SEXP, SEXP points2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type points1(points1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type points2(points2SEXP);
    rcpp_result_gen = Rcpp::wrap(dist3d_pt2pt_pair_cpp(points1, points2));
    return rcpp_result_gen;
END_RCPP
}
// dist3d_pt2line_pair_cpp
NumericVector dist3d_pt2line_pair_cpp(NumericMatrix points, DataFrame lines_df);
RcppExport SEXP _GISnetwork3D_dist3d_pt2line_pair_cpp(SEXP pointsSEXP, SEXP lines_dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type lines_df(lines_dfSEXP);
    rcpp_result_gen = Rcpp::wrap(dist3d_pt2line_pair_cpp(points, lines_df));
    return rcpp_result_gen;
END_RCPP
}
// getFirstNode_cpp
NumericMatrix getFirstNode_cpp(const DataFrame line_df);
RcppExport SEXP _GISnetwork3D_getFirstNode_cpp(SEXP line_dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame >::type line_df(line_dfSEXP);
    rcpp_result_gen = Rcpp::wrap(getFirstNode_cpp(line_df));
    return rcpp_result_gen;
END_RCPP
}
// getLastNode_cpp
NumericMatrix getLastNode_cpp(const DataFrame line_df);
RcppExport SEXP _GISnetwork3D_getLastNode_cpp(SEXP line_dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame >::type line_df(line_dfSEXP);
    rcpp_result_gen = Rcpp::wrap(getLastNode_cpp(line_df));
    return rcpp_result_gen;
END_RCPP
}
// getNodeIndex_cpp
IntegerVector getNodeIndex_cpp(const DataFrame line_df);
RcppExport SEXP _GISnetwork3D_getNodeIndex_cpp(SEXP line_dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame >::type line_df(line_dfSEXP);
    rcpp_result_gen = Rcpp::wrap(getNodeIndex_cpp(line_df));
    return rcpp_result_gen;
END_RCPP
}
// knn3d_p2p_cpp
DataFrame knn3d_p2p_cpp(const DataFrame pt1, const DataFrame pt2, const int k);
RcppExport SEXP _GISnetwork3D_knn3d_p2p_cpp(SEXP pt1SEXP, SEXP pt2SEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame >::type pt1(pt1SEXP);
    Rcpp::traits::input_parameter< const DataFrame >::type pt2(pt2SEXP);
    Rcpp::traits::input_parameter< const int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(knn3d_p2p_cpp(pt1, pt2, k));
    return rcpp_result_gen;
END_RCPP
}
// len3d_cpp
NumericVector len3d_cpp(DataFrame lines_df);
RcppExport SEXP _GISnetwork3D_len3d_cpp(SEXP lines_dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type lines_df(lines_dfSEXP);
    rcpp_result_gen = Rcpp::wrap(len3d_cpp(lines_df));
    return rcpp_result_gen;
END_RCPP
}
// nearest3d_p2p_cpp
IntegerVector nearest3d_p2p_cpp(const DataFrame pt1, const DataFrame pt2);
RcppExport SEXP _GISnetwork3D_nearest3d_p2p_cpp(SEXP pt1SEXP, SEXP pt2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame >::type pt1(pt1SEXP);
    Rcpp::traits::input_parameter< const DataFrame >::type pt2(pt2SEXP);
    rcpp_result_gen = Rcpp::wrap(nearest3d_p2p_cpp(pt1, pt2));
    return rcpp_result_gen;
END_RCPP
}
// nearest3d_p2l_cpp
IntegerVector nearest3d_p2l_cpp(const DataFrame pt, const DataFrame segments);
RcppExport SEXP _GISnetwork3D_nearest3d_p2l_cpp(SEXP ptSEXP, SEXP segmentsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame >::type pt(ptSEXP);
    Rcpp::traits::input_parameter< const DataFrame >::type segments(segmentsSEXP);
    rcpp_result_gen = Rcpp::wrap(nearest3d_p2l_cpp(pt, segments));
    return rcpp_result_gen;
END_RCPP
}
// segmentise_cpp
List segmentise_cpp(const DataFrame lines_df);
RcppExport SEXP _GISnetwork3D_segmentise_cpp(SEXP lines_dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame >::type lines_df(lines_dfSEXP);
    rcpp_result_gen = Rcpp::wrap(segmentise_cpp(lines_df));
    return rcpp_result_gen;
END_RCPP
}
// snap3d_p2p_cpp
DataFrame snap3d_p2p_cpp(const DataFrame pt1, const DataFrame pt2, const double tolerance);
RcppExport SEXP _GISnetwork3D_snap3d_p2p_cpp(SEXP pt1SEXP, SEXP pt2SEXP, SEXP toleranceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame >::type pt1(pt1SEXP);
    Rcpp::traits::input_parameter< const DataFrame >::type pt2(pt2SEXP);
    Rcpp::traits::input_parameter< const double >::type tolerance(toleranceSEXP);
    rcpp_result_gen = Rcpp::wrap(snap3d_p2p_cpp(pt1, pt2, tolerance));
    return rcpp_result_gen;
END_RCPP
}
// snap3d_p2l_cpp
DataFrame snap3d_p2l_cpp(const DataFrame pt, const DataFrame segments, const double tolerance);
RcppExport SEXP _GISnetwork3D_snap3d_p2l_cpp(SEXP ptSEXP, SEXP segmentsSEXP, SEXP toleranceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame >::type pt(ptSEXP);
    Rcpp::traits::input_parameter< const DataFrame >::type segments(segmentsSEXP);
    Rcpp::traits::input_parameter< const double >::type tolerance(toleranceSEXP);
    rcpp_result_gen = Rcpp::wrap(snap3d_p2l_cpp(pt, segments, tolerance));
    return rcpp_result_gen;
END_RCPP
}
// splitLineV3d_cpp
DataFrame splitLineV3d_cpp(NumericVector x, NumericVector y, NumericVector z, IntegerVector L1, IntegerVector split);
RcppExport SEXP _GISnetwork3D_splitLineV3d_cpp(SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP L1SEXP, SEXP splitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type L1(L1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type split(splitSEXP);
    rcpp_result_gen = Rcpp::wrap(splitLineV3d_cpp(x, y, z, L1, split));
    return rcpp_result_gen;
END_RCPP
}
// withinDist3d_p2p_cpp
DataFrame withinDist3d_p2p_cpp(const DataFrame pt1, const DataFrame pt2, const double dist);
RcppExport SEXP _GISnetwork3D_withinDist3d_p2p_cpp(SEXP pt1SEXP, SEXP pt2SEXP, SEXP distSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame >::type pt1(pt1SEXP);
    Rcpp::traits::input_parameter< const DataFrame >::type pt2(pt2SEXP);
    Rcpp::traits::input_parameter< const double >::type dist(distSEXP);
    rcpp_result_gen = Rcpp::wrap(withinDist3d_p2p_cpp(pt1, pt2, dist));
    return rcpp_result_gen;
END_RCPP
}
// withinDist3d_p_self_cpp
DataFrame withinDist3d_p_self_cpp(const DataFrame pt, const double dist);
RcppExport SEXP _GISnetwork3D_withinDist3d_p_self_cpp(SEXP ptSEXP, SEXP distSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame >::type pt(ptSEXP);
    Rcpp::traits::input_parameter< const double >::type dist(distSEXP);
    rcpp_result_gen = Rcpp::wrap(withinDist3d_p_self_cpp(pt, dist));
    return rcpp_result_gen;
END_RCPP
}
// withinDist3d_l2p_cpp
DataFrame withinDist3d_l2p_cpp(const DataFrame lines_df, const DataFrame pt_df, const double dist);
RcppExport SEXP _GISnetwork3D_withinDist3d_l2p_cpp(SEXP lines_dfSEXP, SEXP pt_dfSEXP, SEXP distSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame >::type lines_df(lines_dfSEXP);
    Rcpp::traits::input_parameter< const DataFrame >::type pt_df(pt_dfSEXP);
    Rcpp::traits::input_parameter< const double >::type dist(distSEXP);
    rcpp_result_gen = Rcpp::wrap(withinDist3d_l2p_cpp(lines_df, pt_df, dist));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GISnetwork3D_blendPT3d_cpp", (DL_FUNC) &_GISnetwork3D_blendPT3d_cpp, 4},
    {"_GISnetwork3D_calCost_net3d_THF_cpp", (DL_FUNC) &_GISnetwork3D_calCost_net3d_THF_cpp, 3},
    {"_GISnetwork3D_calCost_net3d_CHF_cpp", (DL_FUNC) &_GISnetwork3D_calCost_net3d_CHF_cpp, 8},
    {"_GISnetwork3D_calSlope_net3d_cpp", (DL_FUNC) &_GISnetwork3D_calSlope_net3d_cpp, 4},
    {"_GISnetwork3D_closestPT3d_cpp", (DL_FUNC) &_GISnetwork3D_closestPT3d_cpp, 2},
    {"_GISnetwork3D_connect3d_pair_cpp", (DL_FUNC) &_GISnetwork3D_connect3d_pair_cpp, 2},
    {"_GISnetwork3D_connect3d_ManyToMany_cpp", (DL_FUNC) &_GISnetwork3D_connect3d_ManyToMany_cpp, 2},
    {"_GISnetwork3D_dist3d_pt2pt_cpp", (DL_FUNC) &_GISnetwork3D_dist3d_pt2pt_cpp, 2},
    {"_GISnetwork3D_dist3d_pt2line_cpp", (DL_FUNC) &_GISnetwork3D_dist3d_pt2line_cpp, 2},
    {"_GISnetwork3D_dist3d_pt2pt_pair_cpp", (DL_FUNC) &_GISnetwork3D_dist3d_pt2pt_pair_cpp, 2},
    {"_GISnetwork3D_dist3d_pt2line_pair_cpp", (DL_FUNC) &_GISnetwork3D_dist3d_pt2line_pair_cpp, 2},
    {"_GISnetwork3D_getFirstNode_cpp", (DL_FUNC) &_GISnetwork3D_getFirstNode_cpp, 1},
    {"_GISnetwork3D_getLastNode_cpp", (DL_FUNC) &_GISnetwork3D_getLastNode_cpp, 1},
    {"_GISnetwork3D_getNodeIndex_cpp", (DL_FUNC) &_GISnetwork3D_getNodeIndex_cpp, 1},
    {"_GISnetwork3D_knn3d_p2p_cpp", (DL_FUNC) &_GISnetwork3D_knn3d_p2p_cpp, 3},
    {"_GISnetwork3D_len3d_cpp", (DL_FUNC) &_GISnetwork3D_len3d_cpp, 1},
    {"_GISnetwork3D_nearest3d_p2p_cpp", (DL_FUNC) &_GISnetwork3D_nearest3d_p2p_cpp, 2},
    {"_GISnetwork3D_nearest3d_p2l_cpp", (DL_FUNC) &_GISnetwork3D_nearest3d_p2l_cpp, 2},
    {"_GISnetwork3D_segmentise_cpp", (DL_FUNC) &_GISnetwork3D_segmentise_cpp, 1},
    {"_GISnetwork3D_snap3d_p2p_cpp", (DL_FUNC) &_GISnetwork3D_snap3d_p2p_cpp, 3},
    {"_GISnetwork3D_snap3d_p2l_cpp", (DL_FUNC) &_GISnetwork3D_snap3d_p2l_cpp, 3},
    {"_GISnetwork3D_splitLineV3d_cpp", (DL_FUNC) &_GISnetwork3D_splitLineV3d_cpp, 5},
    {"_GISnetwork3D_withinDist3d_p2p_cpp", (DL_FUNC) &_GISnetwork3D_withinDist3d_p2p_cpp, 3},
    {"_GISnetwork3D_withinDist3d_p_self_cpp", (DL_FUNC) &_GISnetwork3D_withinDist3d_p_self_cpp, 2},
    {"_GISnetwork3D_withinDist3d_l2p_cpp", (DL_FUNC) &_GISnetwork3D_withinDist3d_l2p_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_GISnetwork3D(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
