# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

blendPT3d_cpp <- function(nearestPt, firstNode, lastNode, segID) {
    .Call(`_GISnetwork3D_blendPT3d_cpp`, nearestPt, firstNode, lastNode, segID)
}

calCost_net3d_THF_cpp <- function(lines_df, uniqueL1, pSlope) {
    .Call(`_GISnetwork3D_calCost_net3d_THF_cpp`, lines_df, uniqueL1, pSlope)
}

calCost_net3d_CHF_cpp <- function(lines_df, uniqueL1, pSlope, a, b, c, d, e) {
    .Call(`_GISnetwork3D_calCost_net3d_CHF_cpp`, lines_df, uniqueL1, pSlope, a, b, c, d, e)
}

calSlope_net3d_cpp <- function(fromNode_df, toNode_df, uniqueL1, unit) {
    .Call(`_GISnetwork3D_calSlope_net3d_cpp`, fromNode_df, toNode_df, uniqueL1, unit)
}

closestPT3d_cpp <- function(point_df, lines_df) {
    .Call(`_GISnetwork3D_closestPT3d_cpp`, point_df, lines_df)
}

connect3d_pair_cpp <- function(pt1, pt2) {
    .Call(`_GISnetwork3D_connect3d_pair_cpp`, pt1, pt2)
}

connect3d_ManyToMany_cpp <- function(pt1, pt2) {
    .Call(`_GISnetwork3D_connect3d_ManyToMany_cpp`, pt1, pt2)
}

dist3d_pt2pt_cpp <- function(points1, points2) {
    .Call(`_GISnetwork3D_dist3d_pt2pt_cpp`, points1, points2)
}

dist3d_pt2line_cpp <- function(points, lines_df) {
    .Call(`_GISnetwork3D_dist3d_pt2line_cpp`, points, lines_df)
}

dist3d_pt2pt_pair_cpp <- function(points1, points2) {
    .Call(`_GISnetwork3D_dist3d_pt2pt_pair_cpp`, points1, points2)
}

dist3d_pt2line_pair_cpp <- function(points, lines_df) {
    .Call(`_GISnetwork3D_dist3d_pt2line_pair_cpp`, points, lines_df)
}

getFirstNode_cpp <- function(line_df) {
    .Call(`_GISnetwork3D_getFirstNode_cpp`, line_df)
}

getLastNode_cpp <- function(line_df) {
    .Call(`_GISnetwork3D_getLastNode_cpp`, line_df)
}

getNodeIndex_cpp <- function(line_df) {
    .Call(`_GISnetwork3D_getNodeIndex_cpp`, line_df)
}

knn3d_p2p_cpp <- function(pt1, pt2, k) {
    .Call(`_GISnetwork3D_knn3d_p2p_cpp`, pt1, pt2, k)
}

len3d_cpp <- function(lines_df) {
    .Call(`_GISnetwork3D_len3d_cpp`, lines_df)
}

nearest3d_p2p_cpp <- function(pt1, pt2) {
    .Call(`_GISnetwork3D_nearest3d_p2p_cpp`, pt1, pt2)
}

nearest3d_p2l_cpp <- function(pt, segments) {
    .Call(`_GISnetwork3D_nearest3d_p2l_cpp`, pt, segments)
}

segmentise_cpp <- function(lines_df) {
    .Call(`_GISnetwork3D_segmentise_cpp`, lines_df)
}

snap3d_p2p_cpp <- function(pt1, pt2, tolerance) {
    .Call(`_GISnetwork3D_snap3d_p2p_cpp`, pt1, pt2, tolerance)
}

snap3d_p2l_cpp <- function(pt, segments, tolerance) {
    .Call(`_GISnetwork3D_snap3d_p2l_cpp`, pt, segments, tolerance)
}

splitLineV3d_cpp <- function(x, y, z, L1, split) {
    .Call(`_GISnetwork3D_splitLineV3d_cpp`, x, y, z, L1, split)
}

tilePoint_cpp <- function(tile_df, pt) {
    .Call(`_GISnetwork3D_tilePoint_cpp`, tile_df, pt)
}

tileNode_cpp <- function(tile_df, pt, nodeID) {
    .Call(`_GISnetwork3D_tileNode_cpp`, tile_df, pt, nodeID)
}

withinDist3d_p2p_cpp <- function(pt1, pt2, dist) {
    .Call(`_GISnetwork3D_withinDist3d_p2p_cpp`, pt1, pt2, dist)
}

withinDist3d_p_self_cpp <- function(pt, dist) {
    .Call(`_GISnetwork3D_withinDist3d_p_self_cpp`, pt, dist)
}

withinDist3d_l2p_cpp <- function(lines_df, pt_df, dist) {
    .Call(`_GISnetwork3D_withinDist3d_l2p_cpp`, lines_df, pt_df, dist)
}

